packaging: add customization options to main binary
- Respect JAVA_HOME environment variable
- Use script location to determine prefix directory to find JARs
- Define REAPER_CONFIG_DIR environment variable
- Define REAPER_CONFIG environment variable. It is interpreted relative
to REAPER_CONFIG_DIR if it is not an absolute path.
- Define REAPER_HEAP_SIZE environment variable
- Define REAPER_ENABLE_IPV6 environment variable
- Respect REAPER_JAVA_OPTS/JAVA_OPTS environment variable, and make it
possible to specify arguments containing spaces

diff --git a/src/packaging/bin/cassandra-reaper b/src/packaging/bin/cassandra-reaper
--- a/src/packaging/bin/cassandra-reaper
+++ b/src/packaging/bin/cassandra-reaper
@@ -1,5 +1,7 @@
 #!/bin/bash
+
 # Copyright (c) 2014-2015 Spotify AB
+# Copyright (c) 2018 Daniel Miranda
 #
 #  Licensed under the Apache License, Version 2.0 (the "License");
 #  you may not use this file except in compliance with the License.
@@ -13,35 +15,65 @@
 #  See the License for the specific language governing permissions and
 #  limitations under the License.
 
-REAPER_JAR=$(ls -1 server/target/cassandra-reaper-*.jar)
+REAPER_PREFIX=$(cd "$(dirname "${BASH_SOURCE[0]}")"/..; pwd)
 
-if [ $REAPER_JAR ]; then
-    echo "Using reaper in target"
-    CLASS_PATH=$REAPER_JAR
-fi
-
-if [ -z "$CLASS_PATH" ]; then
-  echo "Looking for reaper in /usr/share/cassandra-reaper/"
-  CLASS_PATH="/usr/share/cassandra-reaper/*"
-fi
-
-if [ $# -eq 0 ]; then
-    CONFIG_PATH="/etc/cassandra-reaper/cassandra-reaper.yaml"
+if [ -n "$JAVA_HOME" ]; then
+    JAVA_BIN="${JAVA_HOME}/bin/java"
 else
-    CONFIG_PATH="$@"
+    JAVA_BIN=$(command -v java)
 fi
 
+if ! [ -x "$JAVA_BIN" ]; then
+    echo "Error: failed to find suitable Java executable" >&2
+    exit 1
+fi
+
+for dir in "${REAPER_PREFIX}/server/target" \
+           "${REAPER_PREFIX}/share/cassandra-reaper"
+do
+    REAPER_JAR=$(find "$dir" -name 'cassandra-reaper*.jar' 2>/dev/null \
+                 | head -n1)
+    if [ -f "$REAPER_JAR" ]; then
+        break
+    fi
+done
+
+if ! [ -f "$REAPER_JAR" ]; then
+    echo "Error: failed to find suitable Reaper JAR" >&2
+    exit 1
+fi
+
+echo "Loading reaper from: ${REAPER_JAR}" >&2
+REAPER_CLASSPATH="$(dirname "$REAPER_JAR")/*"
+
+REAPER_CONFIG_DIR=${REAPER_CONFIG_DIR:-/etc/cassandra-reaper}
+REAPER_CONFIG=${REAPER_CONFIG:=cassandra-reaper.yaml}
+
+if [ $# -gt 0 ]; then
+    REAPER_CONFIG_PATH="$1"
+    shift
+elif [[ "$REAPER_CONFIG" != /* ]]; then
+    REAPER_CONFIG_PATH="${REAPER_CONFIG_DIR}/${REAPER_CONFIG}"
+fi
+
+REAPER_HEAP_SIZE=${REAPER_HEAP_SIZE:-2G}
+REAPER_ENABLE_IPV6=${REAPER_ENABLE_IPV6:-0}
 JVM_OPTS=(
     -ea
-    -Xms2G
-    -Xmx2G
-    # Prefer binding to IPv4 network intefaces (when net.ipv6.bindv6only=1). See
-    # http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6342561 (short version:
-    # comment out this entry to enable IPv6 support).
-    -Djava.net.preferIPv4Stack=true
-    )
+    "-Xms${REAPER_HEAP_SIZE}"
+    "-Xmx${REAPER_HEAP_SIZE}")
 
-exec java ${JVM_OPTS[@]} \
-    -cp ${CLASS_PATH} \
-    io.cassandrareaper.ReaperApplication \
-    server ${CONFIG_PATH}
+if ! [[ "$REAPER_ENABLE_IPV6" -eq 1 || "$REAPER_ENABLE_IPV6" = true ]]; then
+    # Prefer binding to IPv4 network interfaces (when net.ipv6.bindv6only=1).
+    # See http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6342561
+    JVM_OPTS+=('-Djava.net.preferIPv4Stack=true')
+fi
+
+# Load the user-provided JVM options while accounting for escapes and quoted
+# arguments with spaces, but without eval.
+IFS=$'\n' JVM_OPTS+=(
+    $(xargs printf '%s\n' <<< "$REAPER_JAVA_OPTS $JAVA_OPTS"))
+
+exec "$JAVA_BIN" "${JVM_OPTS[@]}" \
+    -cp "$REAPER_CLASSPATH" -jar "$REAPER_JAR" \
+    server "${REAPER_CONFIG_PATH}" "$@"
